### ISSUE TITLE
what happens if the song is available on gaana.com but not on youtube???

### ISSUE THREAD

**Issue by askfriends** [vishaltelangre/music-dl#34]
Thanks for the useful script.

what happens if the song is available on gaana.com but not on youtube???

also what if the quality is not same as gaana?

**Comment by vishaltelangre** [comment]
> what happens if the song is available on gaana.com but not on youtube???

In this case, no MP3 file will be download for that specific track. 

In general, `music-dl` searches YouTube for the videos matching the title of a track that it obtained from the provided playlist on a supported provider website (for e.g. gaana.com). It chooses the first video from the search results, converts it into MP3 codec, and then downloads it locally.

  > also what if the quality is not same as gaana?

There is no way to test the quality of a song on YouTube. Since `music-dl` actually downloads songs from YouTube and not from the provider website (e.g. gaana.com), there is no guarantee at all that the download file would match the audio quality to the same track available on that provider website.

Closing this issue for now. Thanks!
